name: elevo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-113.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  result_dart: ^1.1.0
  cron: ^0.5.1
  sqflite: ^2.3.0
  path: ^1.8.3
  asp: ^1.3.0
  uuid: ^3.0.7
  go_router: ^10.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/empty-wallet.svg
    - lib/assets/icons/wallet-money.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/trash.svg
    - lib/assets/icons/forbidden-2.svg
    - lib/assets/icons/refresh-2.svg
    - lib/assets/icons/bill.svg
    - lib/assets/icons/tick-circle.svg
    - lib/assets/icons/logo.svg
    - lib/assets/icons/close.svg
    - lib/assets/icons/arrow-down.svg
    
    - lib/assets/icons/bag.svg
    - lib/assets/icons/car.svg
    - lib/assets/icons/heart.svg
    - lib/assets/icons/home-2.svg
    - lib/assets/icons/money.svg
    - lib/assets/icons/more-circle.svg
    - lib/assets/icons/receipt.svg
    - lib/assets/icons/status-up.svg
    - lib/assets/icons/sun.svg

  fonts:
    - family: Qanelas
      fonts:
        - asset: lib/assets/fonts/Qanelas-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/Qanelas-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Qanelas-SemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/Qanelas-Bold.otf
          weight: 700